name: Build N1 67+o and 67+

on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      days:
        description: 'Number of days.'
        required: true
        default: 60
      minimum_runs:
        description: 'The minimum runs to keep for each workflow.'
        required: true
        default: 6
  schedule:
    - cron: 0 23 * * *      
env:
  UPLOAD_COWTRANSFER: false
  RELEASE: true
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-20.04
    name: Build for ${{ matrix.flippy_name }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - flippy_name: 67+o
            release_name: N1-novpn-67+o.img

    env:
      FLIPPY_NAME: ${{ matrix.flippy_name }}   
      RELEASE_NAME: ${{ matrix.release_name }}
    steps:
    - name: Checkout
      uses: actions/checkout@main
      
    - name: Initialization environment
      run: |     
        version="DZ"
        echo "version=$version"  >> $GITHUB_ENV
        echo "DATE=$(date "+%Y-%m-%d %H:%M:%S")"  >> $GITHUB_ENV
        
        sudo chmod  -R 777 /opt
        cp -r ${FLIPPY_NAME}/opt/* /opt
                
    - name: Download
      run: |
        cd /opt/openwrt_packit
        
        wget  https://github.com/loso3000/temp/releases/download/v1.0.1/openwrt-armvirt-64-default-rootfs.tar.gz
                
    - name: Check Files
      run: |
        cd /opt/openwrt_packit
        ls
                
    - name: Install the package
      run: |
        sudo rm -rf /etc/apt/sources.list.d/* /usr/share/dotnet /usr/local/lib/android /opt/ghc
        sudo -E apt-get -qq update
        sudo -E apt-get -qq install xz-utils btrfs-progs gawk zip unzip curl dosfstools  uuid-runtime
        sudo -E apt-get -qq install git  git-core
        sudo -E apt-get -qq install pigz
        sudo -E apt-get -qq autoremove --purge
        sudo -E apt-get -qq clean
    
    - name: build img
      run: |
        sudo chmod  -R 777 /opt
        cd /opt/openwrt_packit
        sudo chmod +x *.sh
        sudo ./mk_s905d_n1.sh
        
    - name: copy update files
      run: |
        cd /opt/openwrt_packit
        sudo cp files/openwrt-update-amlogic output/openwrt-update-amlogic
        ls ./output
    - name: pigz -9
      run: |
        sudo chmod -R 777 /opt/openwrt_packit/output
        cd /opt/openwrt_packit/output
        sudo pigz -9 ${RELEASE_NAME}
        ls
        echo "::set-output name=status::success"

    - name: Check Files4
      run: |
        cd /opt/openwrt_packit/output
        ls
    - name: Upload Firmware
      uses: actions/upload-artifact@main
      with:
          name: OpenWrt-n1-dz-Firmware
          path: /opt/openwrt_packit/output
 
    - name: 编译后硬盘容量
      if: (!cancelled())
      run: df -hT

    - name: Upload firmware to WeTransfer
      run: |
        curl -fsSL git.io/file-transfer | sh
        ./transfer cow --block 2621440 -s -p 64 --no-progress /opt/openwrt/tmp/$RELEASE_NAME.gz 2>&1 | tee cowtransfer.log
        echo "::warning file=cowtransfer.com::$(cat cowtransfer.log | grep https)"
        echo "::set-output name=url::$(cat cowtransfer.log | grep https | cut -f3 -d" ")"
        
  
